### ISSUE TITLE
running the docker version of geoip-service

### ISSUE THREAD

**Issue by lonnietc** [klauspost/geoip-service#1]
Greetings,

I have been working a bit with your geoip-service and have been able to install your docker version with:

docker pull klauspost/geoip-service

I have also found that you cannot use the docker run command as stated in your document as the " (quote) at the end generates a problem.

docker run --rm -p 127.0.0.1:3000:5000 -v /local/GeoLite2-City.mmdb:/data/geodb.mmdb klauspost/geoip-service"

but can run

docker run --rm -p 127.0.0.1:3000:5000 -v /local/GeoLite2-City.mmdb:/data/geodb.mmdb klauspost/geoip-service

The problem that I am now having is with the following command:

docker run --rm -p 127.0.0.1:3000:5000 -v /local/GeoLite2-City.mmdb:/data/geodb.mmdb klauspost/geoip-service app db="/data/geodb.mmdb" pretty=true

or even just

docker run --rm -p 127.0.0.1:3000:5000 -v /local/GeoLite2-City.mmdb:/data/geodb.mmdb klauspost/geoip-service app pretty=true

it seems that from the "app ..." onwards is causing a problem on my Ubuntu 15.04 system for some reason and I cannot figure out how to pass the "pretty=true" as a command line argument to the geoip-service inside the container.

Can you please advise on how to resolve this?

Thanks,
Lonnie

**Comment by tecnobrat** [comment]
I think you are simply missing some `-`'s.

`docker run --rm -p 127.0.0.1:3000:5000 -v /local/GeoLite2-City.mmdb:/data/geodb.mmdb klauspost/geoip-service app -pretty=true -db=/data/geodb.mmdb`

**Comment by klauspost** [comment]
:+1:
